JavaScript abstraction layer for LB4
strongloop/loopback4-example-javascript pull request #1
Opened 2019-01-09 09:11 UTC by hacksparrow

@bajtos @raymondfeng

How feasible is to create a top-level alternative JavaScript API for LoopBack? Time and effort are two biggest factors we have to consider.

In this PR, I have created the project structure that is would be the first stepping stone for the approach, if we should go ahead with the endeavor. It is basically an optimization of the JS code emitted by TypeScript from the scaffolded LB4 app. It works, but is a total hack, not practical for real-world usage.

2019-01-09 16:16 UTC, raymondfeng commented
@hacksparrow Thank you for putting together a working app using plain JS. Which stage are you on per https://github.com/strongloop/loopback4-example-javascript/pull/1/files#diff-c7375ff11bc41bd2c1fbde6f98f5904a?

2019-01-09 16:21 UTC, raymondfeng commented on server/controllers/color.controller.js
> +], ColorController.prototype, "create", null);
We can probably introduce a helper method for method decoration.

2019-01-09 17:18 UTC, hacksparrow commented
> Which stage are you on 

Stage e.

2019-01-10 12:07 UTC, bajtos requested changes
It's great that we have a fully working JavaScript application that we can use as a playground for verifying different experiments around the JavaScript APIs and developer experience 👍 

I strongly feel we need several more iterations on cleaning up the code and APIs. Right now, the code is very TypeScript-centric and would feel very strange for somebody with JavaScript background only. Let's find better abstractions that will make it more ergonomic to write LB4 apps in JavaScript and also let the application code use more of idiomatic JavaScript constructs and other widely-adopted conventions.

I see four major areas where I'd like us to abandon decorator-based approach and find a solution that's more JS-centric.

1. Dependency injection: constructor-level, property-level, method-level.
2. Model definition, including model-property definition and configuration of model-level settings.
3. Remoting metadata, especially at controller-method level.
4. Additional metadata that can be contributed by decorators defined by extensions, e.g. `@authenticate('jwt')` for a controller method or `@validate('email')` for a model property.

2019-01-10 12:07 UTC, bajtos commented on server/application.js
> +class Lb4Application extends boot.BootMixin(serviceProxy.ServiceMixin(repository.RepositoryMixin(rest.RestApplication))) {
Let's use object destructuring to get rid of namespaces like `boot` and `serviceProxy`. This comment applies to all JavaScript files.

```js
const {BootMixin} = require('@loopback/boot');
const {ServiceMixin} = require('@loopback/service-proxy');
// ...

class Lb4Application extends BootMixin(ServiceMixin(/*...*/)) {
}
```

2019-01-10 12:07 UTC, bajtos commented on server/controllers/color.controller.js
> +let ColorController = class ColorController {
Let's simplify class definitions - same comment applies to all other places where we are defining a new class.

```suggestion
class ColorController {
```

2019-01-10 12:07 UTC, bajtos commented on server/controllers/color.controller.js
> +const param = helpers.param;
```js
const {decorate, metadata, param} = require('../../lib/helpers.js');
```

2019-01-10 12:07 UTC, bajtos commented on server/controllers/color.controller.js
> +  }
In this approach, the method implementation is far away from its metadata. In my experience, it's an anti-pattern that makes the code difficult to read and maintain. We should look for ways how to allow developers to keep both the implementation and the metadata together in one place.

For example:

```js
class ColorController {

  /** find() **/
  async find(filter) {
    return await this.colorRepository.find(filter);
  }

  static findSpec = {
    verb: 'get',
    path: '/colors',
    spec: {
      responses: { /* ... */ },
    };
  }

    /** create() **/
    // etc.
}
```

Another example leveraging [class fields](https://github.com/tc39/proposal-class-fields) and a helper function we can provide:

```js
class ColorController {
  find = remoteMethod(
    verb: 'get',
    path: '/colors',
    spec: {
      responses: { /* ... */ },
    },
    handler: async function find(filter) {
      return await this.colorRepository.find(filter);
    });
}
```

There are many ways how to approach this problem, I would like us to look for a solution that would be more ergonomic and better fit JavaScript mindset (as opposed to TypeScript).

Few more ideas:
- If we accept the downsides of having the spec in a different place from the implementation, then it may be better to use design-first approach and provide OpenAPI spec for the entire controller class in one place, instead of using awkward decorator helpers that are not really helpful in JavaScript.
- Maybe we should not support controller classes in JavaScript and ask developers to build their REST APIs using handler routes? This is closer to Express style and I think it will make it easier for us to come up with an ergonomic API for defining such routes.

2019-01-10 12:07 UTC, bajtos commented on server/controllers/color.controller.js
> +  constructor(colorRepository) {
When reading this code, it's not clear that `colorRepository` will receive the value via dependency injection :(

In AngularJS 1.x, they used the following syntax for DI, I found it pretty easy to use and understand. It makes we wonder if we could draw some inspiration there?

```js
const someFunc = ['colorRepository', function(colorRepository) {
  // ...
}];
```

2019-01-10 12:07 UTC, bajtos commented on server/controllers/color.controller.js
> +  param(0, rest.requestBody()),
Specifying parameter indexes manually & explicitly is cumbersome. When inserting a new parameter in between existing params, one has to edit other indices. Such change will also make the diff more difficult to read.

Before:

```js
param(0, /* first param */),
param(1, /* second param */),
```

after:

```js
param(0, /* first param */),
param(1, /* new param */),
param(2, /* formerly second param */),
```

IMO, we should find a way how to infer the index automatically from the order in which the metadata was listed. Take a look at LB3 metadata for an example:

```js
remoteMethod('create', {
  accepts: [
    {arg: 'body', source: 'body'}, // first param
    {/* second param */},
    // etc.
  ],
});
```

2019-01-10 12:07 UTC, bajtos commented on server/controllers/color.controller.js
> +  metadata("design:returntype", Promise)
I would prefer to avoid the need to specify design-type metadata. I believe we use design-type metadata as a sugar that allows us to infer certain aspects of OpenAPI spec from metadata provided by TypeScript, thus allowing the user to leave it out from the OpenAPI spec passed to various decorators.

In JavaScript, instead of using design-type metadata, I would prefer to specify types in OpenAPI spec directly.

2019-01-10 12:07 UTC, bajtos commented on server/models/color.model.js
> +  repository.property({
When defining models, the decorators are just helpers filling out metadata that can be set directly on the model class. When defining the models from JavaScript, I would prefer use to use those APIs directly.

```js
const definition = new ModelDefinition('Color')
  .addProperty('id', {type: 'number', id: true})
  .addProperty('value', 'string');

class Color extends Entity {
  constructor(data) {
    super(data);
  }
};

Color.definition = definition;
```

In the future, if [class fields](https://github.com/tc39/proposal-class-fields) make it into the spec & runtime, this code could be further simplified as follows:

```js
class Color extends Entity {
  static definition = new ModelDefinition('Color')
    .addProperty('id', {type: 'number', id: true})
    .addProperty('value', 'string');

  constructor(data) {
    super(data);
  }
};
```

2019-01-10 12:13 UTC, bajtos commented on server/controllers/color.controller.js
> +  }
> use design-first approach and provide OpenAPI spec for the entire controller class in one place

An example to better illustrate what I meant.

```js
const spec = {
  '/colors': {
    get: {
      'x-controller-method': 'create',
      responses: {/*...*/}
    },
    // ...
  }
  // ...
};

class ColorController {
  async find(filter) {
    return await this.colorRepository.find(filter);
  });
  // ...;
}

ColorController.spec = spec;
// or perhaps invoke `@api` decorator via a sugar helper
api(ColorController, spec)
```

> ask developers to build their REST APIs using handler routes? 

To support grouping of routes in a single file, we can add app/server-level helper to register multiple routes defined on a single object instance. Then the routes could be defined as follows:

```js
// lib/color-routes.js
module.exports = {
  find: remoteMethod(
    verb: 'get',
    path: '/colors',
    spec: {
      responses: { /* ... */ },
    },
    handler: async function find(filter) {
      return await this.colorRepository.find(filter);
    }
  ),

  create: remoteMethod(
    // ...
  )
}
```

Or make it even more declarative:

```js
// lib/color-routes.js
module.exports = {
  find: {
    verb: 'get',
    path: '/colors',
    spec: {
      responses: { /* ... */ },
    },
    handler: async function find(filter) {
      return await this.colorRepository.find(filter);
    }
  },

  create: {
    // ...
  }
}
```

Please treat those code snippets as mock-ups for illustration and inspiration, not as a proposal for the final syntax.

2019-01-10 12:23 UTC, hacksparrow commented
Thanks @bajtos and @raymondfeng, I will begin work on the next round of optimization.

2019-01-18 08:41 UTC, bajtos commented on server/sequence.js
> +  function (target, key) { context.inject(SequenceActions.FIND_ROUTE)(target, key, 0); },
This does not seem like an improvement to me - the parameter index is still hard-coded.

2022-09-06 19:58 UTC, closed without merging